networks:
  default:
    name: ${NETWORK_NAME:-app_network}
    driver: bridge

services:

  backend:
    container_name: ${BACKEND_CONTAINER_NAME:-whaticket_backend}
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${MYSQL_HOST:-localhost}
      - DB_USER=${MYSQL_USER:-root}
      - DB_PASS=${MYSQL_PASSWORD:-strongpassword}
      - DB_NAME=${MYSQL_DATABASE:-whaticket}
      - JWT_SECRET=${JWT_SECRET:-3123123213123}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-75756756756}
      - BACKEND_URL=${BACKEND_URL:-http://localhost}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - PROXY_PORT=${PROXY_PORT:-8080}
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox
    ports:
      - ${BACKEND_PORT:-8080}:3000
    volumes:
      - ./backend/public/:/usr/src/app/public/
      - ./backend/.wwebjs_auth/:/usr/src/app/.wwebjs_auth/
    restart: always

  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME:-whaticket_frontend}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - URL_BACKEND=${BACKEND_CONTAINER_NAME:-whaticket_backend}:3000
      - REACT_APP_BACKEND_URL=${BACKEND_URL:-http://localhost}:${PROXY_PORT:-8080}/
      - FRONTEND_SERVER_NAME=${FRONTEND_SERVER_NAME:-frontend_server}
      - BACKEND_SERVER_NAME=${BACKEND_SERVER_NAME:-backend_server}
    ports:
      - ${FRONTEND_PORT:-3000}:80
      - ${FRONTEND_SSL_PORT:-3001}:443
    volumes:
      - ./ssl/certs/:/etc/nginx/ssl/
      - ./ssl/www/:/var/www/letsencrypt/
    restart: always
